/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package android.support.design;

public final class R {
    public static final class anim {
        public static int fab_in=com.wmlives.heihei.R.anim.fab_in;
        public static int fab_out=com.wmlives.heihei.R.anim.fab_out;
        public static int snackbar_in=com.wmlives.heihei.R.anim.snackbar_in;
        public static int snackbar_out=com.wmlives.heihei.R.anim.snackbar_out;
    }
    public static final class attr {
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int behavior_overlapTop=com.wmlives.heihei.R.attr.behavior_overlapTop;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int borderWidth=com.wmlives.heihei.R.attr.borderWidth;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int collapsedTitleTextAppearance=com.wmlives.heihei.R.attr.collapsedTitleTextAppearance;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int contentScrim=com.wmlives.heihei.R.attr.contentScrim;
        
        
        public static int elevation=com.wmlives.heihei.R.attr.elevation;
        
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int errorEnabled=com.wmlives.heihei.R.attr.errorEnabled;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int errorTextAppearance=com.wmlives.heihei.R.attr.errorTextAppearance;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int expandedTitleMargin=com.wmlives.heihei.R.attr.expandedTitleMargin;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int expandedTitleMarginBottom=com.wmlives.heihei.R.attr.expandedTitleMarginBottom;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int expandedTitleMarginEnd=com.wmlives.heihei.R.attr.expandedTitleMarginEnd;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int expandedTitleMarginStart=com.wmlives.heihei.R.attr.expandedTitleMarginStart;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int expandedTitleMarginTop=com.wmlives.heihei.R.attr.expandedTitleMarginTop;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int expandedTitleTextAppearance=com.wmlives.heihei.R.attr.expandedTitleTextAppearance;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>normal</code></td><td>0</td><td></td></tr>
<tr><td><code>mini</code></td><td>1</td><td></td></tr>
</table>
         */
        public static int fabSize=com.wmlives.heihei.R.attr.fabSize;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int headerLayout=com.wmlives.heihei.R.attr.headerLayout;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int hintTextAppearance=com.wmlives.heihei.R.attr.hintTextAppearance;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static int insetForeground=com.wmlives.heihei.R.attr.insetForeground;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int itemBackground=com.wmlives.heihei.R.attr.itemBackground;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int itemIconTint=com.wmlives.heihei.R.attr.itemIconTint;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int itemTextColor=com.wmlives.heihei.R.attr.itemTextColor;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int keylines=com.wmlives.heihei.R.attr.keylines;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int layout_anchor=com.wmlives.heihei.R.attr.layout_anchor;
        /** <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>top</code></td><td>0x30</td><td></td></tr>
<tr><td><code>bottom</code></td><td>0x50</td><td></td></tr>
<tr><td><code>left</code></td><td>0x03</td><td></td></tr>
<tr><td><code>right</code></td><td>0x05</td><td></td></tr>
<tr><td><code>center_vertical</code></td><td>0x10</td><td></td></tr>
<tr><td><code>fill_vertical</code></td><td>0x70</td><td></td></tr>
<tr><td><code>center_horizontal</code></td><td>0x01</td><td></td></tr>
<tr><td><code>fill_horizontal</code></td><td>0x07</td><td></td></tr>
<tr><td><code>center</code></td><td>0x11</td><td></td></tr>
<tr><td><code>fill</code></td><td>0x77</td><td></td></tr>
<tr><td><code>clip_vertical</code></td><td>0x80</td><td></td></tr>
<tr><td><code>clip_horizontal</code></td><td>0x08</td><td></td></tr>
<tr><td><code>start</code></td><td>0x00800003</td><td></td></tr>
<tr><td><code>end</code></td><td>0x00800005</td><td></td></tr>
</table>
         */
        public static int layout_anchorGravity=com.wmlives.heihei.R.attr.layout_anchorGravity;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int layout_behavior=com.wmlives.heihei.R.attr.layout_behavior;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>pin</code></td><td>1</td><td></td></tr>
<tr><td><code>parallax</code></td><td>2</td><td></td></tr>
</table>
         */
        public static int layout_collapseMode=com.wmlives.heihei.R.attr.layout_collapseMode;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int layout_collapseParallaxMultiplier=com.wmlives.heihei.R.attr.layout_collapseParallaxMultiplier;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int layout_keyline=com.wmlives.heihei.R.attr.layout_keyline;
        /** <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>scroll</code></td><td>0x1</td><td></td></tr>
<tr><td><code>exitUntilCollapsed</code></td><td>0x2</td><td></td></tr>
<tr><td><code>enterAlways</code></td><td>0x4</td><td></td></tr>
<tr><td><code>enterAlwaysCollapsed</code></td><td>0x8</td><td></td></tr>
</table>
         */
        public static int layout_scrollFlags=com.wmlives.heihei.R.attr.layout_scrollFlags;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int layout_scrollInterpolator=com.wmlives.heihei.R.attr.layout_scrollInterpolator;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int maxActionInlineWidth=com.wmlives.heihei.R.attr.maxActionInlineWidth;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int menu=com.wmlives.heihei.R.attr.menu;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int pressedTranslationZ=com.wmlives.heihei.R.attr.pressedTranslationZ;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int rippleColor=com.wmlives.heihei.R.attr.rippleColor;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int statusBarBackground=com.wmlives.heihei.R.attr.statusBarBackground;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int statusBarScrim=com.wmlives.heihei.R.attr.statusBarScrim;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int tabBackground=com.wmlives.heihei.R.attr.tabBackground;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tabContentStart=com.wmlives.heihei.R.attr.tabContentStart;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>fill</code></td><td>0</td><td></td></tr>
<tr><td><code>center</code></td><td>1</td><td></td></tr>
</table>
         */
        public static int tabGravity=com.wmlives.heihei.R.attr.tabGravity;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tabIndicatorColor=com.wmlives.heihei.R.attr.tabIndicatorColor;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tabIndicatorHeight=com.wmlives.heihei.R.attr.tabIndicatorHeight;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tabMaxWidth=com.wmlives.heihei.R.attr.tabMaxWidth;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tabMinWidth=com.wmlives.heihei.R.attr.tabMinWidth;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>scrollable</code></td><td>0</td><td></td></tr>
<tr><td><code>fixed</code></td><td>1</td><td></td></tr>
</table>
         */
        public static int tabMode=com.wmlives.heihei.R.attr.tabMode;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tabPadding=com.wmlives.heihei.R.attr.tabPadding;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tabPaddingBottom=com.wmlives.heihei.R.attr.tabPaddingBottom;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tabPaddingEnd=com.wmlives.heihei.R.attr.tabPaddingEnd;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tabPaddingStart=com.wmlives.heihei.R.attr.tabPaddingStart;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tabPaddingTop=com.wmlives.heihei.R.attr.tabPaddingTop;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tabSelectedTextColor=com.wmlives.heihei.R.attr.tabSelectedTextColor;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int tabTextAppearance=com.wmlives.heihei.R.attr.tabTextAppearance;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tabTextColor=com.wmlives.heihei.R.attr.tabTextColor;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int toolbarId=com.wmlives.heihei.R.attr.toolbarId;
    }
    public static final class color {
        public static int error_color=com.wmlives.heihei.R.color.error_color;
        public static int fab_stroke_end_inner_color=com.wmlives.heihei.R.color.fab_stroke_end_inner_color;
        public static int fab_stroke_end_outer_color=com.wmlives.heihei.R.color.fab_stroke_end_outer_color;
        public static int fab_stroke_top_inner_color=com.wmlives.heihei.R.color.fab_stroke_top_inner_color;
        public static int fab_stroke_top_outer_color=com.wmlives.heihei.R.color.fab_stroke_top_outer_color;
        public static int shadow_end_color=com.wmlives.heihei.R.color.shadow_end_color;
        public static int shadow_mid_color=com.wmlives.heihei.R.color.shadow_mid_color;
        public static int shadow_start_color=com.wmlives.heihei.R.color.shadow_start_color;
        public static int snackbar_background_color=com.wmlives.heihei.R.color.snackbar_background_color;
    }
    public static final class dimen {
        public static int appbar_elevation=com.wmlives.heihei.R.dimen.appbar_elevation;
        public static int fab_border_width=com.wmlives.heihei.R.dimen.fab_border_width;
        public static int fab_content_size=com.wmlives.heihei.R.dimen.fab_content_size;
        public static int fab_elevation=com.wmlives.heihei.R.dimen.fab_elevation;
        public static int fab_size_mini=com.wmlives.heihei.R.dimen.fab_size_mini;
        public static int fab_size_normal=com.wmlives.heihei.R.dimen.fab_size_normal;
        public static int fab_translation_z_pressed=com.wmlives.heihei.R.dimen.fab_translation_z_pressed;
        public static int navigation_elevation=com.wmlives.heihei.R.dimen.navigation_elevation;
        public static int navigation_icon_padding=com.wmlives.heihei.R.dimen.navigation_icon_padding;
        public static int navigation_icon_size=com.wmlives.heihei.R.dimen.navigation_icon_size;
        public static int navigation_max_width=com.wmlives.heihei.R.dimen.navigation_max_width;
        public static int navigation_padding_bottom=com.wmlives.heihei.R.dimen.navigation_padding_bottom;
        public static int navigation_padding_top_default=com.wmlives.heihei.R.dimen.navigation_padding_top_default;
        public static int navigation_separator_vertical_padding=com.wmlives.heihei.R.dimen.navigation_separator_vertical_padding;
        public static int snackbar_action_inline_max_width=com.wmlives.heihei.R.dimen.snackbar_action_inline_max_width;
        public static int snackbar_background_corner_radius=com.wmlives.heihei.R.dimen.snackbar_background_corner_radius;
        public static int snackbar_elevation=com.wmlives.heihei.R.dimen.snackbar_elevation;
        public static int snackbar_extra_spacing_horizontal=com.wmlives.heihei.R.dimen.snackbar_extra_spacing_horizontal;
        public static int snackbar_max_width=com.wmlives.heihei.R.dimen.snackbar_max_width;
        public static int snackbar_min_width=com.wmlives.heihei.R.dimen.snackbar_min_width;
        public static int snackbar_padding_horizontal=com.wmlives.heihei.R.dimen.snackbar_padding_horizontal;
        public static int snackbar_padding_vertical=com.wmlives.heihei.R.dimen.snackbar_padding_vertical;
        public static int snackbar_padding_vertical_2lines=com.wmlives.heihei.R.dimen.snackbar_padding_vertical_2lines;
        public static int snackbar_text_size=com.wmlives.heihei.R.dimen.snackbar_text_size;
        public static int tab_max_width=com.wmlives.heihei.R.dimen.tab_max_width;
        public static int tab_min_width=com.wmlives.heihei.R.dimen.tab_min_width;
    }
    public static final class drawable {
        public static int fab_background=com.wmlives.heihei.R.drawable.fab_background;
        public static int snackbar_background=com.wmlives.heihei.R.drawable.snackbar_background;
    }
    public static final class id {
        public static int bottom=com.wmlives.heihei.R.id.bottom;
        public static int center=com.wmlives.heihei.R.id.center;
        public static int center_horizontal=com.wmlives.heihei.R.id.center_horizontal;
        public static int center_vertical=com.wmlives.heihei.R.id.center_vertical;
        public static int clip_horizontal=com.wmlives.heihei.R.id.clip_horizontal;
        public static int clip_vertical=com.wmlives.heihei.R.id.clip_vertical;
        public static int end=com.wmlives.heihei.R.id.end;
        public static int enterAlways=com.wmlives.heihei.R.id.enterAlways;
        public static int enterAlwaysCollapsed=com.wmlives.heihei.R.id.enterAlwaysCollapsed;
        public static int exitUntilCollapsed=com.wmlives.heihei.R.id.exitUntilCollapsed;
        public static int fill=com.wmlives.heihei.R.id.fill;
        public static int fill_horizontal=com.wmlives.heihei.R.id.fill_horizontal;
        public static int fill_vertical=com.wmlives.heihei.R.id.fill_vertical;
        public static int fixed=com.wmlives.heihei.R.id.fixed;
        public static int left=com.wmlives.heihei.R.id.left;
        public static int mini=com.wmlives.heihei.R.id.mini;
        public static int none=com.wmlives.heihei.R.id.none;
        public static int normal=com.wmlives.heihei.R.id.normal;
        public static int parallax=com.wmlives.heihei.R.id.parallax;
        public static int pin=com.wmlives.heihei.R.id.pin;
        public static int right=com.wmlives.heihei.R.id.right;
        public static int scroll=com.wmlives.heihei.R.id.scroll;
        public static int scrollable=com.wmlives.heihei.R.id.scrollable;
        public static int start=com.wmlives.heihei.R.id.start;
        public static int top=com.wmlives.heihei.R.id.top;
        public static int view_offset_helper=com.wmlives.heihei.R.id.view_offset_helper;
    }
    public static final class integer {
        public static int snackbar_text_max_lines=com.wmlives.heihei.R.integer.snackbar_text_max_lines;
    }
    public static final class layout {
        public static int design_navigation_item=com.wmlives.heihei.R.layout.design_navigation_item;
        public static int design_navigation_item_header=com.wmlives.heihei.R.layout.design_navigation_item_header;
        public static int design_navigation_item_separator=com.wmlives.heihei.R.layout.design_navigation_item_separator;
        public static int design_navigation_item_subheader=com.wmlives.heihei.R.layout.design_navigation_item_subheader;
        public static int design_navigation_menu=com.wmlives.heihei.R.layout.design_navigation_menu;
        public static int layout_snackbar=com.wmlives.heihei.R.layout.layout_snackbar;
        public static int layout_snackbar_include=com.wmlives.heihei.R.layout.layout_snackbar_include;
        public static int layout_tab_icon=com.wmlives.heihei.R.layout.layout_tab_icon;
        public static int layout_tab_text=com.wmlives.heihei.R.layout.layout_tab_text;
    }
    public static final class string {
        public static int appbar_scrolling_view_behavior=com.wmlives.heihei.R.string.appbar_scrolling_view_behavior;
    }
    public static final class style {
        public static int Base_Widget_Design_TabLayout=com.wmlives.heihei.R.style.Base_Widget_Design_TabLayout;
        public static int TextAppearance_Design_CollapsingToolbar_Expanded=com.wmlives.heihei.R.style.TextAppearance_Design_CollapsingToolbar_Expanded;
        public static int TextAppearance_Design_Error=com.wmlives.heihei.R.style.TextAppearance_Design_Error;
        public static int TextAppearance_Design_Hint=com.wmlives.heihei.R.style.TextAppearance_Design_Hint;
        public static int TextAppearance_Design_Snackbar_Action=com.wmlives.heihei.R.style.TextAppearance_Design_Snackbar_Action;
        public static int TextAppearance_Design_Snackbar_Message=com.wmlives.heihei.R.style.TextAppearance_Design_Snackbar_Message;
        public static int TextAppearance_Design_Tab=com.wmlives.heihei.R.style.TextAppearance_Design_Tab;
        public static int Widget_Design_AppBarLayout=com.wmlives.heihei.R.style.Widget_Design_AppBarLayout;
        public static int Widget_Design_CollapsingToolbar=com.wmlives.heihei.R.style.Widget_Design_CollapsingToolbar;
        public static int Widget_Design_CoordinatorLayout=com.wmlives.heihei.R.style.Widget_Design_CoordinatorLayout;
        public static int Widget_Design_FloatingActionButton=com.wmlives.heihei.R.style.Widget_Design_FloatingActionButton;
        public static int Widget_Design_NavigationView=com.wmlives.heihei.R.style.Widget_Design_NavigationView;
        public static int Widget_Design_ScrimInsetsFrameLayout=com.wmlives.heihei.R.style.Widget_Design_ScrimInsetsFrameLayout;
        public static int Widget_Design_Snackbar=com.wmlives.heihei.R.style.Widget_Design_Snackbar;
        public static int Widget_Design_TabLayout=com.wmlives.heihei.R.style.Widget_Design_TabLayout;
        public static int Widget_Design_TextInputLayout=com.wmlives.heihei.R.style.Widget_Design_TextInputLayout;
    }
    public static final class styleable {
        /** Attributes that can be used with a AppBarLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #AppBarLayout_android_background android:background}</code></td><td></td></tr>
           </table>
           @see #AppBarLayout_android_background
         */
        public static final int[] AppBarLayout = com.wmlives.heihei.R.styleable.AppBarLayout;
        
        public static int AppBarLayout_elevation = com.wmlives.heihei.R.styleable.AppBarLayout_elevation;
        
        /**
          <p>This symbol is the offset where the {@link android.R.attr#background}
          attribute's value can be found in the {@link #AppBarLayout} array.
          @attr name android:background
        */
        public static int AppBarLayout_android_background = com.wmlives.heihei.R.styleable.AppBarLayout_android_background;
        /** Attributes that can be used with a AppBarLayout_LayoutParams.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #AppBarLayout_LayoutParams_layout_scrollFlags android.support.design:layout_scrollFlags}</code></td><td></td></tr>
           <tr><td><code>{@link #AppBarLayout_LayoutParams_layout_scrollInterpolator android.support.design:layout_scrollInterpolator}</code></td><td></td></tr>
           </table>
           @see #AppBarLayout_LayoutParams_layout_scrollFlags
           @see #AppBarLayout_LayoutParams_layout_scrollInterpolator
         */
        public static final int[] AppBarLayout_LayoutParams = com.wmlives.heihei.R.styleable.AppBarLayout_LayoutParams;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#layout_scrollFlags}
          attribute's value can be found in the {@link #AppBarLayout_LayoutParams} array.


          <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>scroll</code></td><td>0x1</td><td></td></tr>
<tr><td><code>exitUntilCollapsed</code></td><td>0x2</td><td></td></tr>
<tr><td><code>enterAlways</code></td><td>0x4</td><td></td></tr>
<tr><td><code>enterAlwaysCollapsed</code></td><td>0x8</td><td></td></tr>
</table>
          @attr name android.support.design:layout_scrollFlags
        */
        public static int AppBarLayout_LayoutParams_layout_scrollFlags = com.wmlives.heihei.R.styleable.AppBarLayout_LayoutParams_layout_scrollFlags;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#layout_scrollInterpolator}
          attribute's value can be found in the {@link #AppBarLayout_LayoutParams} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:layout_scrollInterpolator
        */
        public static int AppBarLayout_LayoutParams_layout_scrollInterpolator = com.wmlives.heihei.R.styleable.AppBarLayout_LayoutParams_layout_scrollInterpolator;
        /** Attributes that can be used with a CollapsingAppBarLayout_LayoutParams.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CollapsingAppBarLayout_LayoutParams_layout_collapseMode android.support.design:layout_collapseMode}</code></td><td></td></tr>
           <tr><td><code>{@link #CollapsingAppBarLayout_LayoutParams_layout_collapseParallaxMultiplier android.support.design:layout_collapseParallaxMultiplier}</code></td><td></td></tr>
           </table>
           @see #CollapsingAppBarLayout_LayoutParams_layout_collapseMode
           @see #CollapsingAppBarLayout_LayoutParams_layout_collapseParallaxMultiplier
         */
        public static final int[] CollapsingAppBarLayout_LayoutParams = com.wmlives.heihei.R.styleable.CollapsingAppBarLayout_LayoutParams;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#layout_collapseMode}
          attribute's value can be found in the {@link #CollapsingAppBarLayout_LayoutParams} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>pin</code></td><td>1</td><td></td></tr>
<tr><td><code>parallax</code></td><td>2</td><td></td></tr>
</table>
          @attr name android.support.design:layout_collapseMode
        */
        public static int CollapsingAppBarLayout_LayoutParams_layout_collapseMode = 
                com.wmlives.heihei.R.styleable.CollapsingAppBarLayout_LayoutParams_layout_collapseMode;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#layout_collapseParallaxMultiplier}
          attribute's value can be found in the {@link #CollapsingAppBarLayout_LayoutParams} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:layout_collapseParallaxMultiplier
        */
        public static int CollapsingAppBarLayout_LayoutParams_layout_collapseParallaxMultiplier = 
                com.wmlives.heihei.R.styleable.CollapsingAppBarLayout_LayoutParams_layout_collapseParallaxMultiplier;
        /** Attributes that can be used with a CollapsingToolbarLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CollapsingToolbarLayout_collapsedTitleTextAppearance android.support.design:collapsedTitleTextAppearance}</code></td><td></td></tr>
           <tr><td><code>{@link #CollapsingToolbarLayout_contentScrim android.support.design:contentScrim}</code></td><td></td></tr>
           <tr><td><code>{@link #CollapsingToolbarLayout_expandedTitleMargin android.support.design:expandedTitleMargin}</code></td><td></td></tr>
           <tr><td><code>{@link #CollapsingToolbarLayout_expandedTitleMarginBottom android.support.design:expandedTitleMarginBottom}</code></td><td></td></tr>
           <tr><td><code>{@link #CollapsingToolbarLayout_expandedTitleMarginEnd android.support.design:expandedTitleMarginEnd}</code></td><td></td></tr>
           <tr><td><code>{@link #CollapsingToolbarLayout_expandedTitleMarginStart android.support.design:expandedTitleMarginStart}</code></td><td></td></tr>
           <tr><td><code>{@link #CollapsingToolbarLayout_expandedTitleMarginTop android.support.design:expandedTitleMarginTop}</code></td><td></td></tr>
           <tr><td><code>{@link #CollapsingToolbarLayout_expandedTitleTextAppearance android.support.design:expandedTitleTextAppearance}</code></td><td></td></tr>
           <tr><td><code>{@link #CollapsingToolbarLayout_statusBarScrim android.support.design:statusBarScrim}</code></td><td></td></tr>
           <tr><td><code>{@link #CollapsingToolbarLayout_toolbarId android.support.design:toolbarId}</code></td><td></td></tr>
           </table>
           @see #CollapsingToolbarLayout_collapsedTitleTextAppearance
           @see #CollapsingToolbarLayout_contentScrim
           @see #CollapsingToolbarLayout_expandedTitleMargin
           @see #CollapsingToolbarLayout_expandedTitleMarginBottom
           @see #CollapsingToolbarLayout_expandedTitleMarginEnd
           @see #CollapsingToolbarLayout_expandedTitleMarginStart
           @see #CollapsingToolbarLayout_expandedTitleMarginTop
           @see #CollapsingToolbarLayout_expandedTitleTextAppearance
           @see #CollapsingToolbarLayout_statusBarScrim
           @see #CollapsingToolbarLayout_toolbarId
         */
        public static final int[] CollapsingToolbarLayout = com.wmlives.heihei.R.styleable.CollapsingToolbarLayout;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#collapsedTitleTextAppearance}
          attribute's value can be found in the {@link #CollapsingToolbarLayout} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:collapsedTitleTextAppearance
        */
        public static int CollapsingToolbarLayout_collapsedTitleTextAppearance = 
                com.wmlives.heihei.R.styleable.CollapsingToolbarLayout_collapsedTitleTextAppearance;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#contentScrim}
          attribute's value can be found in the {@link #CollapsingToolbarLayout} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:contentScrim
        */
        public static int CollapsingToolbarLayout_contentScrim = 
                com.wmlives.heihei.R.styleable.CollapsingToolbarLayout_contentScrim;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#expandedTitleMargin}
          attribute's value can be found in the {@link #CollapsingToolbarLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:expandedTitleMargin
        */
        public static int CollapsingToolbarLayout_expandedTitleMargin = 
                com.wmlives.heihei.R.styleable.CollapsingToolbarLayout_expandedTitleMargin;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#expandedTitleMarginBottom}
          attribute's value can be found in the {@link #CollapsingToolbarLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:expandedTitleMarginBottom
        */
        public static int CollapsingToolbarLayout_expandedTitleMarginBottom = 
                com.wmlives.heihei.R.styleable.CollapsingToolbarLayout_expandedTitleMarginBottom;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#expandedTitleMarginEnd}
          attribute's value can be found in the {@link #CollapsingToolbarLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:expandedTitleMarginEnd
        */
        public static int CollapsingToolbarLayout_expandedTitleMarginEnd = 
                com.wmlives.heihei.R.styleable.CollapsingToolbarLayout_expandedTitleMarginEnd;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#expandedTitleMarginStart}
          attribute's value can be found in the {@link #CollapsingToolbarLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:expandedTitleMarginStart
        */
        public static int CollapsingToolbarLayout_expandedTitleMarginStart = 
                com.wmlives.heihei.R.styleable.CollapsingToolbarLayout_expandedTitleMarginStart;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#expandedTitleMarginTop}
          attribute's value can be found in the {@link #CollapsingToolbarLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:expandedTitleMarginTop
        */
        public static int CollapsingToolbarLayout_expandedTitleMarginTop = 
                com.wmlives.heihei.R.styleable.CollapsingToolbarLayout_expandedTitleMarginTop;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#expandedTitleTextAppearance}
          attribute's value can be found in the {@link #CollapsingToolbarLayout} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:expandedTitleTextAppearance
        */
        public static int CollapsingToolbarLayout_expandedTitleTextAppearance = 
                com.wmlives.heihei.R.styleable.CollapsingToolbarLayout_expandedTitleTextAppearance;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#statusBarScrim}
          attribute's value can be found in the {@link #CollapsingToolbarLayout} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:statusBarScrim
        */
        public static int CollapsingToolbarLayout_statusBarScrim = 
                com.wmlives.heihei.R.styleable.CollapsingToolbarLayout_statusBarScrim;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#toolbarId}
          attribute's value can be found in the {@link #CollapsingToolbarLayout} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:toolbarId
        */
        public static int CollapsingToolbarLayout_toolbarId = 
                com.wmlives.heihei.R.styleable.CollapsingToolbarLayout_toolbarId;
        /** Attributes that can be used with a CoordinatorLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CoordinatorLayout_keylines android.support.design:keylines}</code></td><td></td></tr>
           <tr><td><code>{@link #CoordinatorLayout_statusBarBackground android.support.design:statusBarBackground}</code></td><td></td></tr>
           </table>
           @see #CoordinatorLayout_keylines
           @see #CoordinatorLayout_statusBarBackground
         */
        public static final int[] CoordinatorLayout = com.wmlives.heihei.R.styleable.CoordinatorLayout;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#keylines}
          attribute's value can be found in the {@link #CoordinatorLayout} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:keylines
        */
        public static int CoordinatorLayout_keylines = 
                com.wmlives.heihei.R.styleable.CoordinatorLayout_keylines;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#statusBarBackground}
          attribute's value can be found in the {@link #CoordinatorLayout} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:statusBarBackground
        */
        public static int CoordinatorLayout_statusBarBackground = 
                com.wmlives.heihei.R.styleable.CoordinatorLayout_statusBarBackground;
        /** Attributes that can be used with a CoordinatorLayout_LayoutParams.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CoordinatorLayout_LayoutParams_android_layout_gravity android:layout_gravity}</code></td><td></td></tr>
           <tr><td><code>{@link #CoordinatorLayout_LayoutParams_layout_anchor android.support.design:layout_anchor}</code></td><td></td></tr>
           <tr><td><code>{@link #CoordinatorLayout_LayoutParams_layout_anchorGravity android.support.design:layout_anchorGravity}</code></td><td></td></tr>
           <tr><td><code>{@link #CoordinatorLayout_LayoutParams_layout_behavior android.support.design:layout_behavior}</code></td><td></td></tr>
           <tr><td><code>{@link #CoordinatorLayout_LayoutParams_layout_keyline android.support.design:layout_keyline}</code></td><td></td></tr>
           </table>
           @see #CoordinatorLayout_LayoutParams_android_layout_gravity
           @see #CoordinatorLayout_LayoutParams_layout_anchor
           @see #CoordinatorLayout_LayoutParams_layout_anchorGravity
           @see #CoordinatorLayout_LayoutParams_layout_behavior
           @see #CoordinatorLayout_LayoutParams_layout_keyline
         */
        public static final int[] CoordinatorLayout_LayoutParams = com.wmlives.heihei.R.styleable.CoordinatorLayout_LayoutParams;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#layout_gravity}
          attribute's value can be found in the {@link #CoordinatorLayout_LayoutParams} array.
          @attr name android:layout_gravity
        */
        public static int CoordinatorLayout_LayoutParams_android_layout_gravity = 
                com.wmlives.heihei.R.styleable.CoordinatorLayout_LayoutParams_android_layout_gravity;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#layout_anchor}
          attribute's value can be found in the {@link #CoordinatorLayout_LayoutParams} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:layout_anchor
        */
        public static int CoordinatorLayout_LayoutParams_layout_anchor = 
                com.wmlives.heihei.R.styleable.CoordinatorLayout_LayoutParams_layout_anchor;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#layout_anchorGravity}
          attribute's value can be found in the {@link #CoordinatorLayout_LayoutParams} array.


          <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>top</code></td><td>0x30</td><td></td></tr>
<tr><td><code>bottom</code></td><td>0x50</td><td></td></tr>
<tr><td><code>left</code></td><td>0x03</td><td></td></tr>
<tr><td><code>right</code></td><td>0x05</td><td></td></tr>
<tr><td><code>center_vertical</code></td><td>0x10</td><td></td></tr>
<tr><td><code>fill_vertical</code></td><td>0x70</td><td></td></tr>
<tr><td><code>center_horizontal</code></td><td>0x01</td><td></td></tr>
<tr><td><code>fill_horizontal</code></td><td>0x07</td><td></td></tr>
<tr><td><code>center</code></td><td>0x11</td><td></td></tr>
<tr><td><code>fill</code></td><td>0x77</td><td></td></tr>
<tr><td><code>clip_vertical</code></td><td>0x80</td><td></td></tr>
<tr><td><code>clip_horizontal</code></td><td>0x08</td><td></td></tr>
<tr><td><code>start</code></td><td>0x00800003</td><td></td></tr>
<tr><td><code>end</code></td><td>0x00800005</td><td></td></tr>
</table>
          @attr name android.support.design:layout_anchorGravity
        */
        public static int CoordinatorLayout_LayoutParams_layout_anchorGravity = 
                com.wmlives.heihei.R.styleable.CoordinatorLayout_LayoutParams_layout_anchorGravity;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#layout_behavior}
          attribute's value can be found in the {@link #CoordinatorLayout_LayoutParams} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:layout_behavior
        */
        public static int CoordinatorLayout_LayoutParams_layout_behavior = 
                com.wmlives.heihei.R.styleable.CoordinatorLayout_LayoutParams_layout_behavior;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#layout_keyline}
          attribute's value can be found in the {@link #CoordinatorLayout_LayoutParams} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:layout_keyline
        */
        public static int CoordinatorLayout_LayoutParams_layout_keyline = 
                com.wmlives.heihei.R.styleable.CoordinatorLayout_LayoutParams_layout_keyline;
        /** Attributes that can be used with a FloatingActionButton.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #FloatingActionButton_android_background android:background}</code></td><td></td></tr>
           <tr><td><code>{@link #FloatingActionButton_borderWidth android.support.design:borderWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #FloatingActionButton_fabSize android.support.design:fabSize}</code></td><td></td></tr>
           <tr><td><code>{@link #FloatingActionButton_pressedTranslationZ android.support.design:pressedTranslationZ}</code></td><td></td></tr>
           <tr><td><code>{@link #FloatingActionButton_rippleColor android.support.design:rippleColor}</code></td><td></td></tr>
           </table>
           @see #FloatingActionButton_android_background
           @see #FloatingActionButton_borderWidth
           @see #FloatingActionButton_fabSize
           @see #FloatingActionButton_pressedTranslationZ
           @see #FloatingActionButton_rippleColor
         */
        public static final int[] FloatingActionButton = com.wmlives.heihei.R.styleable.FloatingActionButton;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#background}
          attribute's value can be found in the {@link #FloatingActionButton} array.
          @attr name android:background
        */
        public static int FloatingActionButton_android_background = 
                com.wmlives.heihei.R.styleable.FloatingActionButton_android_background;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#borderWidth}
          attribute's value can be found in the {@link #FloatingActionButton} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:borderWidth
        */
        public static int FloatingActionButton_borderWidth = 
                com.wmlives.heihei.R.styleable.FloatingActionButton_borderWidth;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#fabSize}
          attribute's value can be found in the {@link #FloatingActionButton} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>normal</code></td><td>0</td><td></td></tr>
<tr><td><code>mini</code></td><td>1</td><td></td></tr>
</table>
          @attr name android.support.design:fabSize
        */
        public static int FloatingActionButton_fabSize = 
                com.wmlives.heihei.R.styleable.FloatingActionButton_fabSize;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#pressedTranslationZ}
          attribute's value can be found in the {@link #FloatingActionButton} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:pressedTranslationZ
        */
        public static int FloatingActionButton_pressedTranslationZ = 
                com.wmlives.heihei.R.styleable.FloatingActionButton_pressedTranslationZ;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#rippleColor}
          attribute's value can be found in the {@link #FloatingActionButton} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:rippleColor
        */
        public static int FloatingActionButton_rippleColor = 
                com.wmlives.heihei.R.styleable.FloatingActionButton_rippleColor;
        /** Attributes that can be used with a NavigationView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #NavigationView_android_background android:background}</code></td><td></td></tr>
           <tr><td><code>{@link #NavigationView_android_fitsSystemWindows android:fitsSystemWindows}</code></td><td></td></tr>
           <tr><td><code>{@link #NavigationView_android_maxWidth android:maxWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #NavigationView_headerLayout android.support.design:headerLayout}</code></td><td></td></tr>
           <tr><td><code>{@link #NavigationView_itemBackground android.support.design:itemBackground}</code></td><td></td></tr>
           <tr><td><code>{@link #NavigationView_itemIconTint android.support.design:itemIconTint}</code></td><td></td></tr>
           <tr><td><code>{@link #NavigationView_itemTextColor android.support.design:itemTextColor}</code></td><td></td></tr>
           <tr><td><code>{@link #NavigationView_menu android.support.design:menu}</code></td><td></td></tr>
           </table>
           @see #NavigationView_android_background
           @see #NavigationView_android_fitsSystemWindows
           @see #NavigationView_android_maxWidth
           @see #NavigationView_headerLayout
           @see #NavigationView_itemBackground
           @see #NavigationView_itemIconTint
           @see #NavigationView_itemTextColor
           @see #NavigationView_menu
         */
        public static final int[] NavigationView = com.wmlives.heihei.R.styleable.NavigationView;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#background}
          attribute's value can be found in the {@link #NavigationView} array.
          @attr name android:background
        */
        public static int NavigationView_android_background = 
                com.wmlives.heihei.R.styleable.NavigationView_android_background;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#fitsSystemWindows}
          attribute's value can be found in the {@link #NavigationView} array.
          @attr name android:fitsSystemWindows
        */
        public static int NavigationView_android_fitsSystemWindows = 
                com.wmlives.heihei.R.styleable.NavigationView_android_fitsSystemWindows;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#maxWidth}
          attribute's value can be found in the {@link #NavigationView} array.
          @attr name android:maxWidth
        */
        public static int NavigationView_android_maxWidth = 
                com.wmlives.heihei.R.styleable.NavigationView_android_maxWidth;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#headerLayout}
          attribute's value can be found in the {@link #NavigationView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:headerLayout
        */
        public static int NavigationView_headerLayout = 
                com.wmlives.heihei.R.styleable.NavigationView_headerLayout;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#itemBackground}
          attribute's value can be found in the {@link #NavigationView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:itemBackground
        */
        public static int NavigationView_itemBackground = 
                com.wmlives.heihei.R.styleable.NavigationView_itemBackground;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#itemIconTint}
          attribute's value can be found in the {@link #NavigationView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:itemIconTint
        */
        public static int NavigationView_itemIconTint = 
                com.wmlives.heihei.R.styleable.NavigationView_itemIconTint;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#itemTextColor}
          attribute's value can be found in the {@link #NavigationView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:itemTextColor
        */
        public static int NavigationView_itemTextColor = 
                com.wmlives.heihei.R.styleable.NavigationView_itemTextColor;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#menu}
          attribute's value can be found in the {@link #NavigationView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:menu
        */
        public static int NavigationView_menu = 
                com.wmlives.heihei.R.styleable.NavigationView_menu;
        /** Attributes that can be used with a ScrimInsetsFrameLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ScrimInsetsFrameLayout_insetForeground android.support.design:insetForeground}</code></td><td></td></tr>
           </table>
           @see #ScrimInsetsFrameLayout_insetForeground
         */
        public static final int[] ScrimInsetsFrameLayout = com.wmlives.heihei.R.styleable.ScrimInsetsFrameLayout;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#insetForeground}
          attribute's value can be found in the {@link #ScrimInsetsFrameLayout} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          @attr name android.support.design:insetForeground
        */
        public static int ScrimInsetsFrameLayout_insetForeground = 
                com.wmlives.heihei.R.styleable.ScrimInsetsFrameLayout_insetForeground;
        /** Attributes that can be used with a ScrollingViewBehavior_Params.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ScrollingViewBehavior_Params_behavior_overlapTop android.support.design:behavior_overlapTop}</code></td><td></td></tr>
           </table>
           @see #ScrollingViewBehavior_Params_behavior_overlapTop
         */
        public static final int[] ScrollingViewBehavior_Params = com.wmlives.heihei.R.styleable.ScrollingViewBehavior_Params;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#behavior_overlapTop}
          attribute's value can be found in the {@link #ScrollingViewBehavior_Params} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:behavior_overlapTop
        */
        public static int ScrollingViewBehavior_Params_behavior_overlapTop = 
                com.wmlives.heihei.R.styleable.ScrollingViewBehavior_Params_behavior_overlapTop;
        /** Attributes that can be used with a SnackbarLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #SnackbarLayout_android_maxWidth android:maxWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #SnackbarLayout_maxActionInlineWidth android.support.design:maxActionInlineWidth}</code></td><td></td></tr>
           </table>
           @see #SnackbarLayout_android_maxWidth
           @see #SnackbarLayout_maxActionInlineWidth
         */
        public static final int[] SnackbarLayout = com.wmlives.heihei.R.styleable.SnackbarLayout;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#maxWidth}
          attribute's value can be found in the {@link #SnackbarLayout} array.
          @attr name android:maxWidth
        */
        public static int SnackbarLayout_android_maxWidth = 
                com.wmlives.heihei.R.styleable.SnackbarLayout_android_maxWidth;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#maxActionInlineWidth}
          attribute's value can be found in the {@link #SnackbarLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:maxActionInlineWidth
        */
        public static int SnackbarLayout_maxActionInlineWidth = 
                com.wmlives.heihei.R.styleable.SnackbarLayout_maxActionInlineWidth;
        /** Attributes that can be used with a TabLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #TabLayout_tabBackground android.support.design:tabBackground}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabContentStart android.support.design:tabContentStart}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabGravity android.support.design:tabGravity}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabIndicatorColor android.support.design:tabIndicatorColor}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabIndicatorHeight android.support.design:tabIndicatorHeight}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabMaxWidth android.support.design:tabMaxWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabMinWidth android.support.design:tabMinWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabMode android.support.design:tabMode}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabPadding android.support.design:tabPadding}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabPaddingBottom android.support.design:tabPaddingBottom}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabPaddingEnd android.support.design:tabPaddingEnd}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabPaddingStart android.support.design:tabPaddingStart}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabPaddingTop android.support.design:tabPaddingTop}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabSelectedTextColor android.support.design:tabSelectedTextColor}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabTextAppearance android.support.design:tabTextAppearance}</code></td><td></td></tr>
           <tr><td><code>{@link #TabLayout_tabTextColor android.support.design:tabTextColor}</code></td><td></td></tr>
           </table>
           @see #TabLayout_tabBackground
           @see #TabLayout_tabContentStart
           @see #TabLayout_tabGravity
           @see #TabLayout_tabIndicatorColor
           @see #TabLayout_tabIndicatorHeight
           @see #TabLayout_tabMaxWidth
           @see #TabLayout_tabMinWidth
           @see #TabLayout_tabMode
           @see #TabLayout_tabPadding
           @see #TabLayout_tabPaddingBottom
           @see #TabLayout_tabPaddingEnd
           @see #TabLayout_tabPaddingStart
           @see #TabLayout_tabPaddingTop
           @see #TabLayout_tabSelectedTextColor
           @see #TabLayout_tabTextAppearance
           @see #TabLayout_tabTextColor
         */
        public static final int[] TabLayout = com.wmlives.heihei.R.styleable.TabLayout;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabBackground}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:tabBackground
        */
        public static int TabLayout_tabBackground = 
                com.wmlives.heihei.R.styleable.TabLayout_tabBackground;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabContentStart}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:tabContentStart
        */
        public static int TabLayout_tabContentStart = 
                com.wmlives.heihei.R.styleable.TabLayout_tabContentStart;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabGravity}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>fill</code></td><td>0</td><td></td></tr>
<tr><td><code>center</code></td><td>1</td><td></td></tr>
</table>
          @attr name android.support.design:tabGravity
        */
        public static int TabLayout_tabGravity = 
                com.wmlives.heihei.R.styleable.TabLayout_tabGravity;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabIndicatorColor}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:tabIndicatorColor
        */
        public static int TabLayout_tabIndicatorColor = 
                com.wmlives.heihei.R.styleable.TabLayout_tabIndicatorColor;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabIndicatorHeight}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:tabIndicatorHeight
        */
        public static int TabLayout_tabIndicatorHeight = 
                com.wmlives.heihei.R.styleable.TabLayout_tabIndicatorHeight;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabMaxWidth}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:tabMaxWidth
        */
        public static int TabLayout_tabMaxWidth = 
                com.wmlives.heihei.R.styleable.TabLayout_tabMaxWidth;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabMinWidth}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:tabMinWidth
        */
        public static int TabLayout_tabMinWidth = 
                com.wmlives.heihei.R.styleable.TabLayout_tabMinWidth;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabMode}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>scrollable</code></td><td>0</td><td></td></tr>
<tr><td><code>fixed</code></td><td>1</td><td></td></tr>
</table>
          @attr name android.support.design:tabMode
        */
        public static int TabLayout_tabMode = 
                com.wmlives.heihei.R.styleable.TabLayout_tabMode;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabPadding}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:tabPadding
        */
        public static int TabLayout_tabPadding = 
                com.wmlives.heihei.R.styleable.TabLayout_tabPadding;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabPaddingBottom}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:tabPaddingBottom
        */
        public static int TabLayout_tabPaddingBottom = 
                com.wmlives.heihei.R.styleable.TabLayout_tabPaddingBottom;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabPaddingEnd}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:tabPaddingEnd
        */
        public static int TabLayout_tabPaddingEnd = 
                com.wmlives.heihei.R.styleable.TabLayout_tabPaddingEnd;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabPaddingStart}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:tabPaddingStart
        */
        public static int TabLayout_tabPaddingStart = 
                com.wmlives.heihei.R.styleable.TabLayout_tabPaddingStart;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabPaddingTop}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:tabPaddingTop
        */
        public static int TabLayout_tabPaddingTop = com.wmlives.heihei.R.styleable.TabLayout_tabPaddingTop;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabSelectedTextColor}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:tabSelectedTextColor
        */
        public static int TabLayout_tabSelectedTextColor = 
                com.wmlives.heihei.R.styleable.TabLayout_tabSelectedTextColor;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabTextAppearance}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:tabTextAppearance
        */
        public static int TabLayout_tabTextAppearance = 
                com.wmlives.heihei.R.styleable.TabLayout_tabTextAppearance;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#tabTextColor}
          attribute's value can be found in the {@link #TabLayout} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:tabTextColor
        */
        public static int TabLayout_tabTextColor = 
                com.wmlives.heihei.R.styleable.TabLayout_tabTextColor;
        /** Attributes that can be used with a TextInputLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #TextInputLayout_android_hint android:hint}</code></td><td></td></tr>
           <tr><td><code>{@link #TextInputLayout_errorEnabled android.support.design:errorEnabled}</code></td><td></td></tr>
           <tr><td><code>{@link #TextInputLayout_errorTextAppearance android.support.design:errorTextAppearance}</code></td><td></td></tr>
           <tr><td><code>{@link #TextInputLayout_hintTextAppearance android.support.design:hintTextAppearance}</code></td><td></td></tr>
           </table>
           @see #TextInputLayout_android_hint
           @see #TextInputLayout_errorEnabled
           @see #TextInputLayout_errorTextAppearance
           @see #TextInputLayout_hintTextAppearance
         */
        public static final int[] TextInputLayout = com.wmlives.heihei.R.styleable.TextInputLayout;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#hint}
          attribute's value can be found in the {@link #TextInputLayout} array.
          @attr name android:hint
        */
        public static int TextInputLayout_android_hint = 
                com.wmlives.heihei.R.styleable.TextInputLayout_android_hint;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#errorEnabled}
          attribute's value can be found in the {@link #TextInputLayout} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android.support.design:errorEnabled
        */
        public static int TextInputLayout_errorEnabled = 
                com.wmlives.heihei.R.styleable.TextInputLayout_errorEnabled;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#errorTextAppearance}
          attribute's value can be found in the {@link #TextInputLayout} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:errorTextAppearance
        */
        public static int TextInputLayout_errorTextAppearance = 
                com.wmlives.heihei.R.styleable.TextInputLayout_errorTextAppearance;
        /**
          <p>This symbol is the offset where the {@link android.support.design.R.attr#hintTextAppearance}
          attribute's value can be found in the {@link #TextInputLayout} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android.support.design:hintTextAppearance
        */
        public static int TextInputLayout_hintTextAppearance = 
                com.wmlives.heihei.R.styleable.TextInputLayout_hintTextAppearance;
    };
}
